
package StudentSurveySystem;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.GridLayout;
import java.awt.event.WindowEvent;
import javax.swing.SwingConstants;
import java.awt.event.WindowAdapter;
import StudentSurveySystem.Inheritance;

public class AdministratorMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdministratorMenu
     */
    public AdministratorMenu() {
            
        initComponents();
        this.addWindowListener(
            new WindowAdapter() { 
                public void windowClosing(WindowEvent evt) {
                    UserMenu um = new UserMenu();
                    um.show();
                }
            } 
        ); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataAnalysisbtn = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        editQues = new javax.swing.JButton();
        chgPass = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrator Menu");
        setResizable(false);

        dataAnalysisbtn.setText("Data Analysis");
        dataAnalysisbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataAnalysisbtnActionPerformed(evt);
            }
        });

        reset.setText("Reset Survey");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        editQues.setText("Edit Survey Question");
        editQues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editQuesActionPerformed(evt);
            }
        });

        chgPass.setText("Change Password");
        chgPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chgPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dataAnalysisbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editQues, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(chgPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(dataAnalysisbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editQues, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chgPass, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dataAnalysisbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataAnalysisbtnActionPerformed
        // TODO add your handling code here:
        AnalysisForm af = new AnalysisForm();
        af.show();
    }//GEN-LAST:event_dataAnalysisbtnActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        Inheritance.record.clear();
    }//GEN-LAST:event_resetActionPerformed
    
    private void editQuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editQuesActionPerformed
        // TODO add your handling code here:
        int option;
        do {
            JPanel panel = new JPanel();
            JComboBox<String> jcb = new JComboBox<>(Inheritance.question);
            JTextField newQues = new JTextField();
            panel.setLayout(new GridLayout(4, 1));
            panel.add(new JLabel("Choose question to edit", SwingConstants.CENTER));
            panel.add(jcb);
            panel.add(new JLabel("Your new Question", SwingConstants.CENTER));
            panel.add(newQues);
            String[] options = new String[]{"OK", "Cancel"};
            option = JOptionPane.showOptionDialog(null, panel, "Edit Survey Question", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[1]);
            if(option == 0) {
                int select = jcb.getSelectedIndex();
                if (newQues.getText().isEmpty())
                    JOptionPane.showMessageDialog(null, "Please enter the survey question", "Survey Question Error", JOptionPane.ERROR_MESSAGE);
                else {
                    Inheritance.question[select] = newQues.getText();
                    JOptionPane.showMessageDialog(null, "Question changed succcessfully", "Congratulation", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            
        } while (option==0);
        
        FormFunction ff = new FormFunction();
        try {
            ff.writeQuestion();
        } catch (Exception ex) {
            Logger.getLogger(AdministratorMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_editQuesActionPerformed

    private void chgPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chgPassActionPerformed
        // TODO add your handling code here:
        int option = 0;
        do {
            JPanel panel = new JPanel();
            JLabel label = new JLabel("Enter new password:");
            JPasswordField pass = new JPasswordField(10);
            JLabel label1 = new JLabel("Repeat new password:");
            JPasswordField pass1 = new JPasswordField(10);
            panel.setLayout(new GridLayout(4, 1));
            panel.add(label);
            panel.add(pass);
            panel.add(label1);
            panel.add(pass1);
            String[] options = new String[]{"OK", "Cancel"};
            option = JOptionPane.showOptionDialog(null, panel, "Change Password", JOptionPane.YES_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[1]);
            if (option == 0) {
                String x = new String(pass.getPassword());
                String y = new String(pass1.getPassword());
                if (pass.getPassword().length == 0 || pass1.getPassword().length == 0) {
                    JOptionPane.showMessageDialog(null, "Please enter something", "Password Error", JOptionPane.ERROR_MESSAGE);
                } else if (x.contentEquals(y)) {
                    Administrator admin = new Administrator();
                    admin.setPassword(y);
                    try {
                        admin.write();
                    } catch (Exception ex) {
                        Logger.getLogger(AdministratorMenu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    JOptionPane.showMessageDialog(null, "Password Confirmed", "Password changed successfully", JOptionPane.INFORMATION_MESSAGE);
                    option = 1;
                } else {
                    JOptionPane.showMessageDialog(null, "Password does not match", "Password Error", JOptionPane.ERROR_MESSAGE);
                }

            }
        } while (option == 0);
        
        
           
    }//GEN-LAST:event_chgPassActionPerformed

    public boolean callSetPass() {
        int option = 0;
        JPanel panel = new JPanel();
        JLabel label = new JLabel("Enter new password:");
        JPasswordField pass = new JPasswordField(10);

        panel.add(label);
        panel.add(pass);

        String[] options = new String[]{"OK", "Cancel"};
        option = JOptionPane.showOptionDialog(null, panel, "Administrator First Login", JOptionPane.YES_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[1]);
        if (option == 0) {
            password = new String(pass.getPassword());
            option = 1;
            return true;
        } else {
            return false;
        }
    }

    public String getPassword() {
        return password;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministratorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministratorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministratorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministratorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministratorMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chgPass;
    private javax.swing.JButton dataAnalysisbtn;
    private javax.swing.JButton editQues;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
    private String password;
}
