package StudentSurveySystem;

import StudentSurveySystem.Inheritance;
import java.io.PrintStream;
import java.io.ByteArrayOutputStream;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

public class AnalysisForm extends javax.swing.JFrame {

    /**
     * Creates new form EditSurvey
     */
    public AnalysisForm() {
        initComponents();
        group2Visibility(false);
    }
    
    public void group2Visibility(boolean visibility) {
        age.setVisible(visibility);
        q1.setVisible(visibility);
        q2.setVisible(visibility);
        q3.setVisible(visibility);
        q4.setVisible(visibility);
        q5.setVisible(visibility);
        list.setVisible(visibility);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton11 = new javax.swing.JRadioButton();
        buttonGroup2 = new javax.swing.ButtonGroup();
        subjectCB = new javax.swing.JComboBox();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        all = new javax.swing.JRadioButton();
        report = new javax.swing.JRadioButton();
        analyse = new javax.swing.JButton();
        age = new javax.swing.JRadioButton();
        q1 = new javax.swing.JRadioButton();
        q2 = new javax.swing.JRadioButton();
        q3 = new javax.swing.JRadioButton();
        q4 = new javax.swing.JRadioButton();
        q5 = new javax.swing.JRadioButton();
        list = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        buttonGroup1.add(jRadioButton11);
        jRadioButton11.setText("Question 5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Subject Data Analysis");
        setResizable(false);

        subjectCB.setModel(new javax.swing.DefaultComboBoxModel(Inheritance.subject));

        buttonGroup1.add(male);
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        buttonGroup1.add(female);
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(all);
        all.setText("All");
        all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allActionPerformed(evt);
            }
        });

        buttonGroup1.add(report);
        report.setText("Generate Report");
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });

        analyse.setText("Analyse");
        analyse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyseActionPerformed(evt);
            }
        });

        buttonGroup2.add(age);
        age.setText("Age");

        buttonGroup2.add(q1);
        q1.setText("Question 1");
        q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(q2);
        q2.setText("Question 2");
        q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(q3);
        q3.setText("Question 3");
        q3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3ActionPerformed(evt);
            }
        });

        buttonGroup2.add(q4);
        q4.setText("Question 4");
        q4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4ActionPerformed(evt);
            }
        });

        buttonGroup2.add(q5);
        q5.setText("Question 5");
        q5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5ActionPerformed(evt);
            }
        });

        buttonGroup2.add(list);
        list.setText("List Survey");
        list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Subject Data Analysis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(subjectCB, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(79, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(female)
                            .addComponent(male)
                            .addComponent(all)
                            .addComponent(report))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q1)
                            .addComponent(age)
                            .addComponent(q2)
                            .addComponent(q4)
                            .addComponent(q5)
                            .addComponent(q3)
                            .addComponent(list))
                        .addGap(140, 140, 140))))
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(analyse, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(subjectCB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(male)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(female)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(all)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(report))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(age)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(q1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(q2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(q3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(q4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(list)
                .addGap(12, 12, 12)
                .addComponent(analyse, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(528, 459));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void analyseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyseActionPerformed
        // TODO add your handling code here:
        
        do {
            if(buttonGroup1.getSelection() == null) {
                JOptionPane.showMessageDialog(null, "Please select an option from the left", "Selection Error", JOptionPane.ERROR_MESSAGE);
                break;
            }
            if (!report.isSelected()) {
                if(buttonGroup2.getSelection() == null) {
                    JOptionPane.showMessageDialog(null, "Please select an option from the right", "Selection Error", JOptionPane.ERROR_MESSAGE);
                    break;
                }
            }
            

            dana.Initialise();

            int subIndex = subjectCB.getSelectedIndex();
            switch(subIndex) {
                case 0:
                    dana.setSubid("PRG1203");
                    break;
                case 1:
                    dana.setSubid("CSC1202");
                    break;
                case 2:
                    dana.setSubid("SEG1201");
                    break;
                case 3:
                    dana.setSubid("WEB1201");
                    break;
            }

            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            PrintStream old = System.out;
            PrintStream ps = new PrintStream(baos);

            if (male.isSelected() || female.isSelected() || all.isSelected()) {        

                System.setOut(ps);

                if (age.isSelected() == true)
                    dana.printAge();
                else if (q1.isSelected() == true)
                    dana.printQues(0);
                else if (q2.isSelected() == true)
                    dana.printQues(1);
                else if (q3.isSelected() == true)
                    dana.printQues(2);
                else if (q4.isSelected() == true)
                    dana.printQues(3);
                else if (q5.isSelected() == true)
                    dana.printQues(4);
                else if (list.isSelected() == true)
                    dana.printAll();

                System.setOut(old);
                JOptionPane.showMessageDialog(null, baos.toString(), "Analysis Results", JOptionPane.PLAIN_MESSAGE);

            } else if (report.isSelected()) {
                System.setOut(ps);
                dana.generateReport();
                System.setOut(old);
                File file = new File("Report.txt");
                if (!file.exists()) {
                    try {
                        file.createNewFile();
                    } catch (IOException ex) {
                        Logger.getLogger(AnalysisForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                    
                try {
                    PrintWriter pw = new PrintWriter(file);
                    pw.print(baos.toString());
                    pw.close();
                    JOptionPane.showMessageDialog(null, "File created successfully", "Analysis Results", JOptionPane.INFORMATION_MESSAGE);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(AnalysisForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } while (false);
        
    }//GEN-LAST:event_analyseActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
        group2Visibility(true);
        dana.setGenderOption(1);
    }//GEN-LAST:event_maleActionPerformed

    private void q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2ActionPerformed

    private void q4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4ActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
       // TODO add your handling code here:
        group2Visibility(true);
        dana.setGenderOption(2);
    }//GEN-LAST:event_femaleActionPerformed

    private void allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allActionPerformed
        // TODO add your handling code here:
        group2Visibility(true);
        dana.setGenderOption(3);
    }//GEN-LAST:event_allActionPerformed

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        // TODO add your handling code here:
        group2Visibility(false);
        dana.setGenderOption(4);
    }//GEN-LAST:event_reportActionPerformed

    private void q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1ActionPerformed

    private void q3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3ActionPerformed

    private void q5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5ActionPerformed

    private void listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalysisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalysisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalysisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalysisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalysisForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton age;
    private javax.swing.JRadioButton all;
    private javax.swing.JButton analyse;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton list;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton q1;
    private javax.swing.JRadioButton q2;
    private javax.swing.JRadioButton q3;
    private javax.swing.JRadioButton q4;
    private javax.swing.JRadioButton q5;
    private javax.swing.JRadioButton report;
    private javax.swing.JComboBox subjectCB;
    // End of variables declaration//GEN-END:variables
    
    private DataAnalysis dana = new DataAnalysis();
}
