package StudentSurveySystem;

import StudentSurveySystem.Inheritance;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

public class Survey extends javax.swing.JFrame {

    /**
     * Creates new form SurveyApplication
     */
    public Survey() {
        initComponents();
        this.addWindowListener(
            new WindowAdapter() { 
                public void windowClosing(WindowEvent evt) {
                    UserMenu um = new UserMenu();
                    um.show();
                }
            } 
        );
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderBG = new javax.swing.ButtonGroup();
        q1BG = new javax.swing.ButtonGroup();
        q2BG = new javax.swing.ButtonGroup();
        q3BG = new javax.swing.ButtonGroup();
        q4BG = new javax.swing.ButtonGroup();
        q5BG = new javax.swing.ButtonGroup();
        jRadioButton33 = new javax.swing.JRadioButton();
        jRadioButton34 = new javax.swing.JRadioButton();
        jRadioButton35 = new javax.swing.JRadioButton();
        jRadioButton36 = new javax.swing.JRadioButton();
        jRadioButton37 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        subjectCB = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        q11 = new javax.swing.JRadioButton();
        q12 = new javax.swing.JRadioButton();
        q13 = new javax.swing.JRadioButton();
        q14 = new javax.swing.JRadioButton();
        q15 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ques1 = new javax.swing.JLabel();
        ques2 = new javax.swing.JLabel();
        ques3 = new javax.swing.JLabel();
        ques4 = new javax.swing.JLabel();
        ques5 = new javax.swing.JLabel();
        q21 = new javax.swing.JRadioButton();
        q22 = new javax.swing.JRadioButton();
        q23 = new javax.swing.JRadioButton();
        q24 = new javax.swing.JRadioButton();
        q25 = new javax.swing.JRadioButton();
        q31 = new javax.swing.JRadioButton();
        q32 = new javax.swing.JRadioButton();
        q33 = new javax.swing.JRadioButton();
        q34 = new javax.swing.JRadioButton();
        q35 = new javax.swing.JRadioButton();
        q41 = new javax.swing.JRadioButton();
        q42 = new javax.swing.JRadioButton();
        q43 = new javax.swing.JRadioButton();
        q44 = new javax.swing.JRadioButton();
        q45 = new javax.swing.JRadioButton();
        q51 = new javax.swing.JRadioButton();
        q52 = new javax.swing.JRadioButton();
        q53 = new javax.swing.JRadioButton();
        q54 = new javax.swing.JRadioButton();
        q55 = new javax.swing.JRadioButton();
        age = new javax.swing.JSpinner();

        q1BG.add(jRadioButton33);
        jRadioButton33.setText("1");

        q1BG.add(jRadioButton34);
        jRadioButton34.setText("2");

        q1BG.add(jRadioButton35);
        jRadioButton35.setText("3");

        q1BG.add(jRadioButton36);
        jRadioButton36.setText("4");

        q1BG.add(jRadioButton37);
        jRadioButton37.setText("5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Student Survey");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Survey");

        jLabel2.setText("Gender:");

        genderBG.add(male);
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        genderBG.add(female);
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        jLabel3.setText("Age:");

        jLabel4.setText("Subject:");

        subjectCB.setModel(new javax.swing.DefaultComboBoxModel(Inheritance.subject));
        subjectCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectCBActionPerformed(evt);
            }
        });

        jLabel5.setText("1. ");

        q1BG.add(q11);
        q11.setText("1");
        q11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q11ActionPerformed(evt);
            }
        });

        q1BG.add(q12);
        q12.setText("2");
        q12.setActionCommand("");
        q12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q12ActionPerformed(evt);
            }
        });

        q1BG.add(q13);
        q13.setText("3");
        q13.setActionCommand("");
        q13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q13ActionPerformed(evt);
            }
        });

        q1BG.add(q14);
        q14.setText("4");
        q14.setActionCommand("");
        q14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q14ActionPerformed(evt);
            }
        });

        q1BG.add(q15);
        q15.setText("5");
        q15.setActionCommand("");
        q15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q15ActionPerformed(evt);
            }
        });

        jLabel6.setText("2. ");

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jLabel7.setText("3. ");

        jLabel8.setText("4. ");

        jLabel9.setText("5. ");

        ques1.setText(Inheritance.question[0]);

        ques2.setText(Inheritance.question[1]);

        ques3.setText(Inheritance.question[2]);

        ques4.setText(Inheritance.question[3]);

        ques5.setText(Inheritance.question[4]);

        q2BG.add(q21);
        q21.setText("1");
        q21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q21ActionPerformed(evt);
            }
        });

        q2BG.add(q22);
        q22.setText("2");
        q22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q22ActionPerformed(evt);
            }
        });

        q2BG.add(q23);
        q23.setText("3");
        q23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q23ActionPerformed(evt);
            }
        });

        q2BG.add(q24);
        q24.setText("4");
        q24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q24ActionPerformed(evt);
            }
        });

        q2BG.add(q25);
        q25.setText("5");
        q25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q25ActionPerformed(evt);
            }
        });

        q3BG.add(q31);
        q31.setText("1");
        q31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q31ActionPerformed(evt);
            }
        });

        q3BG.add(q32);
        q32.setText("2");
        q32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q32ActionPerformed(evt);
            }
        });

        q3BG.add(q33);
        q33.setText("3");
        q33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q33ActionPerformed(evt);
            }
        });

        q3BG.add(q34);
        q34.setText("4");
        q34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q34ActionPerformed(evt);
            }
        });

        q3BG.add(q35);
        q35.setText("5");
        q35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q35ActionPerformed(evt);
            }
        });

        q4BG.add(q41);
        q41.setText("1");
        q41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q41ActionPerformed(evt);
            }
        });

        q4BG.add(q42);
        q42.setText("2");
        q42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q42ActionPerformed(evt);
            }
        });

        q4BG.add(q43);
        q43.setText("3");
        q43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q43ActionPerformed(evt);
            }
        });

        q4BG.add(q44);
        q44.setText("4");
        q44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q44ActionPerformed(evt);
            }
        });

        q4BG.add(q45);
        q45.setText("5");
        q45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q45ActionPerformed(evt);
            }
        });

        q5BG.add(q51);
        q51.setText("1");
        q51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q51ActionPerformed(evt);
            }
        });

        q5BG.add(q52);
        q52.setText("2");
        q52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q52ActionPerformed(evt);
            }
        });

        q5BG.add(q53);
        q53.setText("3");
        q53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q53ActionPerformed(evt);
            }
        });

        q5BG.add(q54);
        q54.setText("4");
        q54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q54ActionPerformed(evt);
            }
        });

        q5BG.add(q55);
        q55.setText("5");
        q55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q55ActionPerformed(evt);
            }
        });

        age.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(subjectCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ques1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(q11, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                .addGap(66, 66, 66)
                                .addComponent(q12, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                .addGap(66, 66, 66)
                                .addComponent(q13, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                .addGap(66, 66, 66)
                                .addComponent(q14, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                .addGap(66, 66, 66)
                                .addComponent(q15, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ques2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ques3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ques4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ques5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(q21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(66, 66, 66)
                                .addComponent(q22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(66, 66, 66)
                                .addComponent(q23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(66, 66, 66)
                                .addComponent(q24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(66, 66, 66)
                                .addComponent(q25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(q31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(66, 66, 66)
                                .addComponent(q32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(66, 66, 66)
                                .addComponent(q33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(66, 66, 66)
                                .addComponent(q34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(66, 66, 66)
                                .addComponent(q35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(q41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(66, 66, 66)
                                .addComponent(q42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(66, 66, 66)
                                .addComponent(q43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(66, 66, 66)
                                .addComponent(q44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(66, 66, 66)
                                .addComponent(q45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(q51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(66, 66, 66)
                                .addComponent(q52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(66, 66, 66)
                                .addComponent(q53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(66, 66, 66)
                                .addComponent(q54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(66, 66, 66)
                                .addComponent(q55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(115, 115, 115))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(male)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(female))
                            .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(405, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(submit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clear)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(239, 239, 239))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(male)
                    .addComponent(jLabel2)
                    .addComponent(female))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(subjectCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ques1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(q13)
                    .addComponent(q14)
                    .addComponent(q15)
                    .addComponent(q12)
                    .addComponent(q11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ques2))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(q23)
                    .addComponent(q24)
                    .addComponent(q25)
                    .addComponent(q22)
                    .addComponent(q21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ques3))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(q33)
                    .addComponent(q34)
                    .addComponent(q35)
                    .addComponent(q32)
                    .addComponent(q31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ques4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(q43)
                    .addComponent(q44)
                    .addComponent(q45)
                    .addComponent(q42)
                    .addComponent(q41))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ques5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(q53)
                    .addComponent(q54)
                    .addComponent(q55)
                    .addComponent(q52)
                    .addComponent(q51))
                .addGap(0, 47, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(clear))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
        genderF = 'M';
    }//GEN-LAST:event_maleActionPerformed

    private void q11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q11ActionPerformed
        // TODO add your handling code here:
        ques[0] = 1;
    }//GEN-LAST:event_q11ActionPerformed

    private void q12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q12ActionPerformed
        // TODO add your handling code here:
        ques[0] = 2;
    }//GEN-LAST:event_q12ActionPerformed

    private void q21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q21ActionPerformed
        // TODO add your handling code here:
        ques[1] = 1;
    }//GEN-LAST:event_q21ActionPerformed

    private void q22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q22ActionPerformed
        // TODO add your handling code here:
        ques[1] = 2;
    }//GEN-LAST:event_q22ActionPerformed

    private void q31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q31ActionPerformed
        // TODO add your handling code here:
        ques[2] = 1;
    }//GEN-LAST:event_q31ActionPerformed

    private void q32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q32ActionPerformed
        // TODO add your handling code here:
        ques[2] = 2;
    }//GEN-LAST:event_q32ActionPerformed

    private void q41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q41ActionPerformed
        // TODO add your handling code here:
        ques[3] = 1;
    }//GEN-LAST:event_q41ActionPerformed

    private void q42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q42ActionPerformed
        // TODO add your handling code here:
        ques[3] = 2;
    }//GEN-LAST:event_q42ActionPerformed

    private void q51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q51ActionPerformed
        // TODO add your handling code here:
        ques[4] = 1;
    }//GEN-LAST:event_q51ActionPerformed

    private void q52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q52ActionPerformed
        // TODO add your handling code here:
        ques[4] = 2;
    }//GEN-LAST:event_q52ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        ageF = (int)age.getValue();
        do {
            if (genderBG.getSelection() == null) {
                JOptionPane.showMessageDialog(null, "Please select a gender", "Gender Selection Error", JOptionPane.ERROR_MESSAGE);
                break;
            }
            int subIndex = subjectCB.getSelectedIndex();
            switch(subIndex) {
                case 0:
                    courseF = "PRG1203";
                    break;
                case 1:
                    courseF = "CSC1202";
                    break;
                case 2:
                    courseF = "SEG1201";
                    break;
                case 3:
                    courseF = "WEB1201";
                    break;
            }
                
            if (q1BG.getSelection() == null) {
                JOptionPane.showMessageDialog(null, "Question 1 not selected", "Question 1", JOptionPane.ERROR_MESSAGE);
                break;
            }
            
            if (q2BG.getSelection() == null) {
                JOptionPane.showMessageDialog(null, "Question 2 not selected", "Question 2", JOptionPane.ERROR_MESSAGE);
                break;
            }
            
            if (q3BG.getSelection() == null) {
                JOptionPane.showMessageDialog(null, "Question 3 not selected", "Question 3", JOptionPane.ERROR_MESSAGE);
                break;
            }
                    
            if (q4BG.getSelection() == null) {
                JOptionPane.showMessageDialog(null, "Question 4 not selected", "Question 4", JOptionPane.ERROR_MESSAGE);
                break;
            }
            
            if (q5BG.getSelection() == null) {
                JOptionPane.showMessageDialog(null, "Question 5 not selected", "Question 5", JOptionPane.ERROR_MESSAGE);
                break;
            }
            Inheritance.record.add(new Form(genderF, ageF, courseF, ques));
            JOptionPane.showMessageDialog(null, "Congratulation. Your Survey is submitted.\nThank You", "Survey Submitted", JOptionPane.INFORMATION_MESSAGE);
        }while(false);
        
    }//GEN-LAST:event_submitActionPerformed

    private void subjectCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectCBActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        genderBG.clearSelection();
        age.setValue(1);
        subjectCB.setSelectedIndex(0);
        q1BG.clearSelection();
        q2BG.clearSelection();
        q3BG.clearSelection();
        q4BG.clearSelection();
        q5BG.clearSelection();
    }//GEN-LAST:event_clearActionPerformed

    private void q13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q13ActionPerformed
        // TODO add your handling code here:
        ques[0] = 3;
    }//GEN-LAST:event_q13ActionPerformed

    private void q23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q23ActionPerformed
        // TODO add your handling code here:
        ques[1] = 3;
    }//GEN-LAST:event_q23ActionPerformed

    private void q33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q33ActionPerformed
        // TODO add your handling code here:
        ques[2] = 3;
    }//GEN-LAST:event_q33ActionPerformed

    private void q43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q43ActionPerformed
        // TODO add your handling code here:
        ques[3] = 3;
    }//GEN-LAST:event_q43ActionPerformed

    private void q53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q53ActionPerformed
        // TODO add your handling code here:
        ques[4] = 3;
    }//GEN-LAST:event_q53ActionPerformed

    private void q14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q14ActionPerformed
        // TODO add your handling code here:
        ques[0] = 4;
    }//GEN-LAST:event_q14ActionPerformed

    private void q24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q24ActionPerformed
        // TODO add your handling code here:
        ques[1] = 4;
    }//GEN-LAST:event_q24ActionPerformed

    private void q34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q34ActionPerformed
        // TODO add your handling code here:
        ques[2] = 4;
    }//GEN-LAST:event_q34ActionPerformed

    private void q44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q44ActionPerformed
        // TODO add your handling code here:
        ques[3] = 4;
    }//GEN-LAST:event_q44ActionPerformed

    private void q54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q54ActionPerformed
        // TODO add your handling code here:
        ques[4] = 4;
    }//GEN-LAST:event_q54ActionPerformed

    private void q15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q15ActionPerformed
        // TODO add your handling code here:
        ques[0] = 5;
    }//GEN-LAST:event_q15ActionPerformed

    private void q25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q25ActionPerformed
        // TODO add your handling code here:
        ques[1] = 5;
    }//GEN-LAST:event_q25ActionPerformed

    private void q35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q35ActionPerformed
        // TODO add your handling code here:
        ques[2] = 5;
    }//GEN-LAST:event_q35ActionPerformed

    private void q45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q45ActionPerformed
        // TODO add your handling code here:
        ques[3] = 5;
    }//GEN-LAST:event_q45ActionPerformed

    private void q55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q55ActionPerformed
        // TODO add your handling code here:
        ques[4] = 5;
    }//GEN-LAST:event_q55ActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
        genderF = 'F';
    }//GEN-LAST:event_femaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Survey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Survey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Survey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Survey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Survey().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner age;
    private javax.swing.JButton clear;
    private javax.swing.JRadioButton female;
    private javax.swing.ButtonGroup genderBG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton33;
    private javax.swing.JRadioButton jRadioButton34;
    private javax.swing.JRadioButton jRadioButton35;
    private javax.swing.JRadioButton jRadioButton36;
    private javax.swing.JRadioButton jRadioButton37;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton q11;
    private javax.swing.JRadioButton q12;
    private javax.swing.JRadioButton q13;
    private javax.swing.JRadioButton q14;
    private javax.swing.JRadioButton q15;
    private javax.swing.ButtonGroup q1BG;
    private javax.swing.JRadioButton q21;
    private javax.swing.JRadioButton q22;
    private javax.swing.JRadioButton q23;
    private javax.swing.JRadioButton q24;
    private javax.swing.JRadioButton q25;
    private javax.swing.ButtonGroup q2BG;
    private javax.swing.JRadioButton q31;
    private javax.swing.JRadioButton q32;
    private javax.swing.JRadioButton q33;
    private javax.swing.JRadioButton q34;
    private javax.swing.JRadioButton q35;
    private javax.swing.ButtonGroup q3BG;
    private javax.swing.JRadioButton q41;
    private javax.swing.JRadioButton q42;
    private javax.swing.JRadioButton q43;
    private javax.swing.JRadioButton q44;
    private javax.swing.JRadioButton q45;
    private javax.swing.ButtonGroup q4BG;
    private javax.swing.JRadioButton q51;
    private javax.swing.JRadioButton q52;
    private javax.swing.JRadioButton q53;
    private javax.swing.JRadioButton q54;
    private javax.swing.JRadioButton q55;
    private javax.swing.ButtonGroup q5BG;
    private javax.swing.JLabel ques1;
    private javax.swing.JLabel ques2;
    private javax.swing.JLabel ques3;
    private javax.swing.JLabel ques4;
    private javax.swing.JLabel ques5;
    private javax.swing.JComboBox subjectCB;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
    private char genderF;
    private int ageF;
    private String courseF;
    private int[] ques = new int[5];

}
